name: Print Working Directory

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-working-directory:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Working Directory
        run: ls /home/yavuz/

